apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
  namespace: {{ .Values.namespace.name | quote }}
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce