apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-gitops-waves
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: Description
      value: Waves of applications that are dependent to each other, for example Loki, openshift-logging or NetObserv Operator
  project: in-cluster
  source:
    path: gitops-waves/apps/managed
    repoURL: 'https://github.com/tjungbauer/test-app-of-apps'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true