apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-wave-20
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: Description
      value: Application to deploy and configure NetObserv Operator
  project: in-cluster
  source:
    path: gitops-waves/waves/wave-20-netobserv
    repoURL: 'https://github.com/tjungbauer/test-app-of-apps'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true