apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-10-loki-dependencies
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: Description
      value: Application to deploy and configure OpenShift-Logging
  project: in-cluster
  source:
    path: loki-dependency-waves/waves/wave-10-logging
    repoURL: 'https://github.com/tjungbauer/test-app-of-apps'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true