{{- if eq ( .Values.netobserv.enabled | toString) "true" }}
{{- with .Values.netobserv }}
{{- if .bucket }}
{{- if eq ( .bucket.enabled | toString) "true" }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .bucket.name }}
  namespace: {{ .namespace.name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .bucket.syncwave | default "1" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generateBucketName: {{ .bucket.name }}
  storageClassName: {{ .bucket.storageclass | default "openshift-storage.noobaa.io" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
