---
namespace:
  name: netobserv
  create: true

syncwave: '3'


netobserv-namespace: &observ-namespace openshift-logging
bucketname: &bucketname netobserv-bucket
netobservsecret: &netobserv-secret-name netobserv-loki-s3

# SubChart to create the loki secret if required.
# The Secret must contain all required bucket information, while ODF creates a secret and a configmap for example.
# A Kubernetes Job is created, that reads the data from the Secret and ConfigMap and creates a new secret for loki.
helper-loki-bucket-secret:
  # Enable Job creation
  enabled: true

  # Syncwave ... best to do after bucket creation
  syncwave: 2

  # Namespace for logging
  namespace: *observ-namespace

  # Secretname that shall be created 
  secretname: *netobserv-secret-name

  # Name of the bucket
  bucket:
    name: *bucketname

helper-operator:

  # Enable the Console Plugins for the following Operators
  console_plugins:
    - netobserv-plugin

  operators:
    netobserv-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-netobserv-operator
        create: true
      subscription:
        channel: stable
        approval: Automatic
        operatorName: netobserv-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

helper-status-checker:
  enabled: true

  operatorName: network-observability-operator

  # where operator is installed
  namespace:
    name: openshift-netobserv-operator

  serviceAccount:
    create: true
    name: "status-checker-netobserv"
