apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-0-loki-dependencies
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: default
  info:
    - name: Description
      value: Application to prepare stuff (Wave 0) and deploy LokiStack Operator.
  project: in-cluster
  source:
    path: loki-dependency-waves/waves/wave-0-prepare
    repoURL: 'https://github.com/tjungbauer/test-app-of-apps'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
