apiVersion: v2
name: openshift-logging-deployment
description: Installs and configures OpenShift Logging by calling the Chart openshift-logging
version: 1.0.0
dependencies:
  - name: openshift-logging
    version: "1.0.17"
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
